"""empty message

Revision ID: 3956fb68b17a
Revises: 97203e7e5de1
Create Date: 2024-06-19 15:12:08.640980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3956fb68b17a'
down_revision = '97203e7e5de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('branch_uuid', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'branch', ['branch_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_uuid')

    # ### end Alembic commands ###
