"""empty message

Revision ID: 97203e7e5de1
Revises: c103c37af080
Create Date: 2024-06-19 14:56:57.523740

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97203e7e5de1'
down_revision = 'c103c37af080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.drop_constraint('branch_ibfk_1', type_='foreignkey')
        batch_op.drop_column('warehouse_uuid')

    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('branch_uuid', sa.String(length=50), nullable=False))
        batch_op.create_foreign_key(None, 'branch', ['branch_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('branch_uuid')
        batch_op.drop_column('location')

    with op.batch_alter_table('branch', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_uuid', mysql.VARCHAR(collation='utf8mb3_bin', length=50), nullable=False))
        batch_op.create_foreign_key('branch_ibfk_1', 'warehouse', ['warehouse_uuid'], ['uuid'])

    # ### end Alembic commands ###
