"""empty message

Revision ID: c103c37af080
Revises: 
Create Date: 2024-06-19 14:37:33.184832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c103c37af080'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('invoice',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('invoice_type', sa.String(length=50), nullable=False),
    sa.Column('sales_man', sa.String(length=50), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('supplier',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('user',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=400), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('birthday', sa.Date(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('warehouse',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('branch',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('warehouse_uuid', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_uuid'], ['warehouse.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('product',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('category_uuid', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('package', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=250), nullable=True),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['category_uuid'], ['category.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('barcode',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('product_uuid', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_uuid'], ['product.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('invoice_details',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('product_uuid', sa.String(length=50), nullable=True),
    sa.Column('invoice_uuid', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['invoice_uuid'], ['invoice.uuid'], ),
    sa.ForeignKeyConstraint(['product_uuid'], ['product.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('product_warehouse_association',
    sa.Column('product_uuid', sa.String(length=50), nullable=False),
    sa.Column('warehouse_uuid', sa.String(length=50), nullable=False),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['product_uuid'], ['product.uuid'], ),
    sa.ForeignKeyConstraint(['warehouse_uuid'], ['warehouse.uuid'], ),
    sa.PrimaryKeyConstraint('product_uuid', 'warehouse_uuid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_warehouse_association')
    op.drop_table('invoice_details')
    op.drop_table('barcode')
    op.drop_table('product')
    op.drop_table('branch')
    op.drop_table('warehouse')
    op.drop_table('user')
    op.drop_table('supplier')
    op.drop_table('invoice')
    op.drop_table('category')
    # ### end Alembic commands ###
