"""empty message

Revision ID: c5e5d8d17f4a
Revises: 748d880b4788
Create Date: 2024-06-21 16:55:25.976898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e5d8d17f4a'
down_revision = '748d880b4788'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('uuid', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=250), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('action_author', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_uuid', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(None, 'image', ['image_uuid'], ['uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('image_uuid')

    op.drop_table('image')
    # ### end Alembic commands ###
